title: 校长的博客  
description: 个人文章与记录
lang: zh-CN
timezone: Asia/Shanghai

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown

defaults:    #配置front matter内容
  - scope:    #配置规则
      path: ""     #不限制路径，全匹配
      type: posts   #只用于文章
    values:
      layout: post   #自动套用_layouts下的post布局，也就是post.html